{
 "title": "Pwned Service",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Server Errors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_count{path=\"/validate\",code=~\"5..\"}"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{path=\"/validate\"}[30m])/rate(http_request_duration_seconds_count{path=\"/validate\"}[30m])"
    }
   ]
  },
  {
   "title": "Successful requests",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_count{path=\"/validate\",code=~\"2..\"}"
    }
   ]
  },
  {
   "title": "Unsuccessful passwords",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_count{path=\"/validate\",code=~\"4..\"}"
    }
   ]
  },
  {
   "title": "Response Duration (ms)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(increase(\nhttp_request_duration_seconds_bucket{path=\"/validate\"}[30m])) by (le)"
    }
   ]
  }
 ]
}